language: nix
sudo: true
install:
  - echo $HOME/nix-cache
  - ls $HOME/nix-cache
  - if [ -d "$HOME/nix-cache" ]; then mv $HOME/nix-cache /nix; fi
script: nix-build -A package
before_cache: if [ ! -d "$HOME/nix-cache" ]; then cp -a /nix $HOME/nix-cache; fi
cache:
  directories:
    - $HOME/nix-cache

