language: nix
sudo: true
script: nix-build -A package

install: |
  if [ -d "$HOME/nix-cache" ]; then
    rm -rf /nix
    mv $HOME/nix-cache/* /nix
  fi

before_cache: |
  if [ ! -d "$HOME/nix-cache" ]; then
    cp -a /nix $HOME/nix-cache
  fi

cache:
  directories:
    - $HOME/nix-cache

