language: nix
sudo: required

install: |
  if [ "$(ls -A $HOME/nix-cache)" ]; then
    sudo rm -rf /nix/*
    cp -a $HOME/nix-cache/* /nix
  fi

before_cache: |
  if [ ! "$(ls -A $HOME/nix-cache)" ]; then
    cp -a /nix/* $HOME/nix-cache
  fi

cache:
  directories:
    - $HOME/nix-cache

jobs:
  include:
    - name: build
      script: nix-build -A package
    - name: lint
      script: |
        nix-shell -A shell --run "ln -s $NODE_PATH node_modules && npm run lint"

