language: nix
sudo: required

before_install: |
  openssl aes-256-cbc \
    -K $encrypted_e6b209e4eeaf_key -iv $encrypted_e6b209e4eeaf_iv \
    -in gcs-account.json.enc -out gcs-account.json -d

install: |
  if [ "$(ls -A $HOME/nix-cache)" ]; then
    sudo rm -rf /nix/*
    cp -a $HOME/nix-cache/* /nix
  fi

before_script: nix-env -i terraform
script: nix-build -A package

before_cache: |
  if [ ! "$(ls -A $HOME/nix-cache)" ]; then
    cp -a /nix/* $HOME/nix-cache
  fi

cache:
  directories:
    - $HOME/nix-cache

jobs:
  include:
    - stage: Test
      name: Build
    - name: Lint
      script: |
        nix-shell -A shell --run 'ln -s $NODE_PATH node_modules && npm run lint'
    - stage: Deploy
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script: |
          terraform init -input=false \
          && terraform apply -input=false -auto-approve
