language: nix
sudo: required
script: nix-build -A package

install: |
  if [ -d "$HOME/nix-cache" ]; then
    sudo rm -rf /nix/*
    cp -a $HOME/nix-cache/* /nix
  fi

before_cache: |
  if [ ! -d "$HOME/nix-cache" ]; then
    cp -a /nix $HOME/nix-cache
  fi

cache:
  directories:
    - $HOME/nix-cache

